name: RUN Searchhost

on: 
  repository_dispatch:
  workflow_dispatch:  # 触发手动事件
jobs:
   main:
    runs-on: ubuntu-latest
    env:
     BASE: ${{ secrets.BASE }}
     KEYWORD: ${{ secrets.KEYWORD }}
    steps:
      - name: Run searchhost
        run: |
          sudo chmod +x searchhost
          bash ./searchhost -b ${{ secrets.BASE }}
          
      - name: Commit
        id: commit
        continue-on-error: true
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
           git commit -m "Updated at $(date '+%Y-%m-%d %H:%M:%S')"
          git pull --rebase
