name: Test Dns Run

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0  0,12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: dependencies
      run: chmod +x ./q

    - name: delet dns
      run: rm ./dnstest.txt 

    - name: RUN cfproject
      run: ./q --dnssec A afosne.afosne @https://dns.afosne.icu/dns-query > dnstest.txt
    - name: RUN adproject
      run: ./q --dnssec A afosne.afosne @https://adns.afosne.icu/dns-query >> dnstest.txt
    - name: RUN coproject
      run: ./q --dnssec A afosne.afosne @https://cdns.afosne.icu/dns-query >> dnstest.txt
      
    - name: Commit Changes
      run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected in the repository."
            git config core.ignorecase false
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "Updated at $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes detected in the repository."
          fi
